// $Id$
//

unit wxDirDialog;

interface

uses
  Windows, Messages, SysUtils, Classes,wxUtils,WxNonVisibleBaseComponent;

type
  TWxDirDialog = class(TWxNonVisibleBaseComponent,IWxComponentInterface)
  private
    { Private declarations }
        FWx_Class : String;
        FWx_PropertyList : TStringList;
        FWx_Message: String;
        FWx_DefaultDir: String;
        FWx_DirDialogStyle : TWxDirDialogStyleSet;
        procedure AutoInitialize;
        procedure AutoDestroy;

  protected

  public
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;
        function GenerateControlIDs:String;
        function GenerateEnumControlIDs:String;
        function GenerateEventTableEntries(CurrClassName:String):String;
        function GenerateGUIControlCreation:String;
        function GenerateGUIControlDeclaration:String;
        function GenerateHeaderInclude:String;
        function GenerateImageInclude: string;
        function GetEventList:TStringlist;
        function GetIDName:String;
        function GetIDValue:LongInt;
        function GetParameterFromEventName(EventName: string):String;
        function GetPropertyList:TStringList;
        function GetStretchFactor:Integer;
        function GetTypeFromEventName(EventName: string):string;
        function GetWxClassName:String;
        procedure SaveControlOrientation(ControlOrientation:TWxControlOrientation);
        procedure SetIDName(IDName:String);
        procedure SetIDValue(IDValue:longInt);
        procedure SetStretchFactor(intValue:Integer);
        procedure SetWxClassName(wxClassName:String);
        function GetFGColor:string;
        procedure SetFGColor(strValue:String);
        function GetBGColor:string;
        procedure SetBGColor(strValue:String);
        procedure SetProxyFGColorString(value:String);
        procedure SetProxyBGColorString(value:String);
  published
    { Published declarations }
        property Wx_Class : String read FWx_Class write FWx_Class;
        property Wx_Message: String read FWx_Message write FWx_Message;
        property Wx_DefaultDir: String read FWx_DefaultDir write FWx_DefaultDir;
        property Wx_DirDialogStyle:TWxDirDialogStyleSet read FWx_DirDialogStyle write FWx_DirDialogStyle;
  end;

procedure Register;

implementation

procedure Register;
begin
  RegisterComponents('wxWidgets', [TWxDirDialog]);
end;

{ Method to set variable and property values and create objects }
procedure TWxDirDialog.AutoInitialize;
begin
     FWx_PropertyList := TStringList.Create;
     FWx_Class := 'wxDirDialog';
     FWx_Message:='Choose a directory';
     Glyph.Handle:=LoadBitmap(hInstance, 'TWxDirDialog');
end; { of AutoInitialize }

{ Method to free any objects created by AutoInitialize }
procedure TWxDirDialog.AutoDestroy;
begin
     FWx_PropertyList.Free;
end; { of AutoDestroy }

constructor TWxDirDialog.Create(AOwner: TComponent);
begin
     { Call the Create method of the container's parent class       }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables          }
     { (including subcomponent variables) and properties;           }
     { also, it creates objects for properties of standard          }
     { Delphi object types (e.g., TFont, TTimer, TPicture)          }
     { and for any variables marked as objects.                     }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }
     { Code to perform other tasks when the component is created }
     FWx_PropertyList.add('Wx_DirDialogStyle:Dir Dialog Style');     
     FWx_PropertyList.add('wxDD_NEW_DIR_BUTTON:wxDD_NEW_DIR_BUTTON');

     FWx_PropertyList.add('Wx_DefaultDir:Default Dir');
     FWx_PropertyList.add('Wx_Message:Message');
     FWx_PropertyList.add('Name:Name');
     FWx_PropertyList.add('Wx_Class:Base Class');
end;

destructor TWxDirDialog.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

function TWxDirDialog.GenerateControlIDs:String;
begin
     Result:='';
end;


function TWxDirDialog.GenerateEnumControlIDs:String;
begin
     Result:='';
end;

function TWxDirDialog.GenerateEventTableEntries(CurrClassName:String):String;
begin
     Result:='';
end;

function TWxDirDialog.GenerateGUIControlCreation:String;
var
     strType,strStyle:String;
begin
     Result:='';
    strStyle:=GetDirDialogStyleString(self.Wx_DirDialogStyle);
    Result:=Format('%s =  new %s(this, "%s" , "%s"  %s);',[self.Name,self.wx_Class,GetCppString(wx_Message),GetCppString(wx_DefaultDir),strStyle] );
end;

function TWxDirDialog.GenerateGUIControlDeclaration:String;
begin
     Result:='';
     Result:=Format('%s *%s;',[trim(Self.Wx_Class),trim(Self.Name)]);
end;

function TWxDirDialog.GenerateHeaderInclude:String;
begin
     Result:='';
     Result:='#include <wx/dirdlg.h>';
end;

function TWxDirDialog.GenerateImageInclude: string;
begin

end;

function TWxDirDialog.GetEventList:TStringlist;
begin
Result:=nil;
end;

function TWxDirDialog.GetIDName:String;
begin

end;

function TWxDirDialog.GetIDValue:LongInt;
begin
Result:=0;
end;

function TWxDirDialog.GetParameterFromEventName(EventName: string):String;
begin

end;

function TWxDirDialog.GetStretchFactor:Integer;
begin
//
end;

function TWxDirDialog.GetPropertyList:TStringList;
begin
     Result:=FWx_PropertyList;
end;

function TWxDirDialog.GetTypeFromEventName(EventName: string):string;
begin

end;

function TWxDirDialog.GetWxClassName:String;
begin
     if trim(wx_Class) = '' then
        wx_Class:='wxDirDialog';
     Result:=wx_Class;
end;

procedure TWxDirDialog.SaveControlOrientation(ControlOrientation:TWxControlOrientation);
begin
    //
end;

procedure TWxDirDialog.SetIDName(IDName:String);
begin

end;

procedure TWxDirDialog.SetIDValue(IDValue:longInt);
begin

end;

procedure TWxDirDialog.SetStretchFactor(intValue:Integer);
begin
end;

procedure TWxDirDialog.SetWxClassName(wxClassName:String);
begin
     wx_Class:=wxClassName;
end;

function TWxDirDialog.GetFGColor:string;
begin

end;

procedure TWxDirDialog.SetFGColor(strValue:String);
begin
end;
    
function TWxDirDialog.GetBGColor:string;
begin
end;

procedure TWxDirDialog.SetBGColor(strValue:String);
begin
end;
procedure TWxDirDialog.SetProxyFGColorString(value:String);
begin
end;

procedure TWxDirDialog.SetProxyBGColorString(value:String);
begin
end;

end.
 
