unit wxPageSetupDialog;

interface

uses
  Windows, Messages, SysUtils, Classes,wxUtils,WxNonVisibleBaseComponent;

type
  TWxPageSetupDialog = class(TWxNonVisibleBaseComponent,IWxComponentInterface)
  private
    { Private declarations }
        FWx_Class : String;
        FWx_PropertyList : TStringList;
        FMarginTopLeftX: Integer;
        FMarginTopLeftY: Integer;

        FMarginBottomRightX: Integer;
        FMarginBottomRightY: Integer;

        FMinMarginTopLeftX: Integer;
        FMinMarginTopLeftY: Integer;

        FMinMarginBottomRightX: Integer;
        FMinMarginBottomRightY: Integer;

        FPaperId:TWxPaperSizeItem;


        procedure AutoInitialize;
        procedure AutoDestroy;

  protected

  public
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;
        function GenerateControlIDs:String;
        function GenerateEnumControlIDs:String;
        function GenerateEventTableEntries(CurrClassName:String):String;
        function GenerateGUIControlCreation:String;
        function GenerateGUIControlDeclaration:String;
        function GenerateHeaderInclude:String;
        function GenerateImageInclude: string;
        function GetEventList:TStringlist;
        function GetIDName:String;
        function GetIDValue:LongInt;
        function GetParameterFromEventName(EventName: string):String;
        function GetPropertyList:TStringList;
        function GetStretchFactor:Integer;
        function GetTypeFromEventName(EventName: string):string;
        function GetWxClassName:String;
        procedure SaveControlOrientation(ControlOrientation:TWxControlOrientation);
        procedure SetIDName(IDName:String);
        procedure SetIDValue(IDValue:longInt);
        procedure SetStretchFactor(intValue:Integer);
        procedure SetWxClassName(wxClassName:String);
        function GetFGColor:string;
        procedure SetFGColor(strValue:String);
        function GetBGColor:string;
        procedure SetBGColor(strValue:String);
        procedure SetProxyFGColorString(value:String);
        procedure SetProxyBGColorString(value:String);
  published
    { Published declarations }
        property Wx_Class : String read FWx_Class write FWx_Class;

        property Wx_MarginTopLeftX: Integer read FMarginTopLeftX write FMarginTopLeftX;
        property Wx_MarginBottomRightX: Integer read FMarginBottomRightX write FMarginBottomRightX;
        property Wx_MinMarginTopLeftX: Integer read FMinMarginTopLeftX write FMinMarginTopLeftX;
        property Wx_MinMarginBottomRightX: Integer read FMinMarginBottomRightX write FMinMarginBottomRightX;

        property Wx_MarginTopLeftY: Integer read FMarginTopLeftY write FMarginTopLeftY;
        property Wx_MarginBottomRightY: Integer read FMarginBottomRightY write FMarginBottomRightY;
        property Wx_MinMarginTopLeftY: Integer read FMinMarginTopLeftY write FMinMarginTopLeftY;
        property Wx_MinMarginBottomRightY: Integer read FMinMarginBottomRightY write FMinMarginBottomRightY;


        property Wx_PaperId:TWxPaperSizeItem read FPaperId write FPaperId;
    end;

procedure Register;

implementation

procedure Register;
begin
  RegisterComponents('wxWidgets', [TWxPageSetupDialog]);
end;

{ Method to set variable and property values and create objects }
procedure TWxPageSetupDialog.AutoInitialize;
begin
     FWx_PropertyList := TStringList.Create;
     FWx_Class := 'wxPageSetupDialog';
     Glyph.Handle:=LoadBitmap(hInstance, 'TWxPageSetupDialog');

end; { of AutoInitialize }

{ Method to free any objects created by AutoInitialize }
procedure TWxPageSetupDialog.AutoDestroy;
begin
     FWx_PropertyList.Free;
end; { of AutoDestroy }

constructor TWxPageSetupDialog.Create(AOwner: TComponent);
begin
     { Call the Create method of the container's parent class       }
     inherited Create(AOwner);

     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     FWx_PropertyList.add('Name:Name');
     FWx_PropertyList.add('Wx_Class:Base Class');

     FWx_PropertyList.add('Wx_MarginTopLeftX:MarginTopLeftX');
     FWx_PropertyList.add('Wx_MarginBottomRightX:MarginBottomRightX');
     FWx_PropertyList.add('Wx_MinMarginTopLeftX: MinMarginTopLeftX');
     FWx_PropertyList.add('Wx_MinMarginBottomRightX:MinMarginBottomRightX');

     FWx_PropertyList.add('Wx_MarginTopLeftY:MarginTopLeftY');
     FWx_PropertyList.add('Wx_MarginBottomRightY:MarginBottomRightY');
     FWx_PropertyList.add('Wx_MinMarginTopLeftY: MinMarginTopLeftY');
     FWx_PropertyList.add('Wx_MinMarginBottomRightY:MinMarginBottomRightY');

     FWx_PropertyList.add('Wx_PaperId:PaperId');
end;

destructor TWxPageSetupDialog.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

function TWxPageSetupDialog.GenerateControlIDs:String;
begin
     Result:='';
end;

function TWxPageSetupDialog.GenerateEnumControlIDs:String;
begin
     Result:='';
end;

function TWxPageSetupDialog.GenerateEventTableEntries(CurrClassName:String):String;
begin
     Result:='';
end;

function TWxPageSetupDialog.GenerateGUIControlCreation:String;
var
     strFlag,strStyle:String;

begin
    Result:='';
    Result:= self.Name+'_Data = new wxPageSetupDialogData();' ;
    Result:=Result+#13+self.Name+'_Data->SetMarginTopLeft(wxPoint('+Format('%d,%d',[Wx_MarginTopLeftX,Wx_MarginTopLeftY])+'));' ;
    Result:=Result+#13+self.Name+'_Data->SetMarginBottomRight(wxPoint('+Format('%d,%d',[Wx_MarginBottomRightX,Wx_MarginBottomRightY])+'));' ;
    Result:=Result+#13+self.Name+'_Data->SetMinMarginTopLeft(wxPoint('+Format('%d,%d',[Wx_MinMarginTopLeftX,Wx_MinMarginTopLeftY])+'));' ;
    Result:=Result+#13+self.Name+'_Data->SetMinMarginBottomRight(wxPoint('+Format('%d,%d',[Wx_MinMarginBottomRightX,Wx_MinMarginBottomRightY])+'));' ;
    Result:=Result+#13+self.Name+'_Data->SetPaperId('+PaperIDToString(Wx_PaperId) +');';
    Result:=Result+#13+Format('%s =  new %s(this, %s);',[self.Name,self.wx_Class,self.Name+'_Data'] );

end;

function TWxPageSetupDialog.GenerateGUIControlDeclaration:String;
begin
     Result:='';
     Result:=Format('%s *%s;',[trim(Self.Wx_Class),trim(Self.Name)]);
     Result:=Result+#13+Format('wxPageSetupDialogData *%s_Data;',[trim(Self.Name)]);
end;

function TWxPageSetupDialog.GenerateHeaderInclude:String;
begin
     Result:='';
     Result:='#include <wx/printdlg.h>';
     Result:=Result+#13+'#include <wx/cmndata.h>';
end;

function TWxPageSetupDialog.GenerateImageInclude: string;
begin

end;

function TWxPageSetupDialog.GetEventList:TStringlist;
begin
Result:=nil;
end;

function TWxPageSetupDialog.GetIDName:String;
begin

end;

function TWxPageSetupDialog.GetIDValue:LongInt;
begin
    Result :=0;
end;

function TWxPageSetupDialog.GetParameterFromEventName(EventName: string):String;
begin

end;

function TWxPageSetupDialog.GetStretchFactor:Integer;
begin
//
end;

function TWxPageSetupDialog.GetPropertyList:TStringList;
begin
     Result:=FWx_PropertyList;
end;

function TWxPageSetupDialog.GetTypeFromEventName(EventName: string):string;
begin

end;

function TWxPageSetupDialog.GetWxClassName:String;
begin
     if trim(wx_Class) = '' then
        wx_Class:='wxFindReplaceDialog';
     Result:=wx_Class;
end;

procedure TWxPageSetupDialog.SaveControlOrientation(ControlOrientation:TWxControlOrientation);
begin
    //
end;

procedure TWxPageSetupDialog.SetIDName(IDName:String);
begin

end;

procedure TWxPageSetupDialog.SetIDValue(IDValue:longInt);
begin

end;

procedure TWxPageSetupDialog.SetStretchFactor(intValue:Integer);
begin
end;

procedure TWxPageSetupDialog.SetWxClassName(wxClassName:String);
begin
     wx_Class:=wxClassName;
end;

function TWxPageSetupDialog.GetFGColor:string;
begin

end;

procedure TWxPageSetupDialog.SetFGColor(strValue:String);
begin
end;
    
function TWxPageSetupDialog.GetBGColor:string;
begin
end;

procedure TWxPageSetupDialog.SetBGColor(strValue:String);
begin
end;
procedure TWxPageSetupDialog.SetProxyFGColorString(value:String);
begin
end;

procedure TWxPageSetupDialog.SetProxyBGColorString(value:String);
begin
end;

end.
 
