{ ****************************************************************** }
{                                                                    }
{   VCL component TWxStatusBar                                       }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from untitled component definition                     }
{   on 22 Oct 2004 at 17:48                                          }
{                                                                    }
{   Copyright © 2004 by ...                                          }
{                                                                    }
{ ****************************************************************** }

unit WxStatusBar;

interface

uses WinTypes, WinProcs, Messages, SysUtils, Classes, Controls, 
     Forms, Graphics, Comctrls, WxUtils,WxSizerPanel;

type
  TWxStatusBar = class(TStatusBar,IWxComponentInterface,IWxDialogNonInsertableInterface,IWxStatusBarInterface,IWxContainerInterface,IWxContainerAndSizerInterface)
    private
      { Private fields of TWxStatusBar }
        FOrientation : TWxSizerOrientation;
        FSpaceValue : Integer;
        FWx_Caption : String;
        FWx_Class : String;
        FWx_ControlOrientation : TWxControlOrientation;
        FWx_EventList : TStringList;
        FWx_HorizontalAlignment : TWxSizerHorizontalAlignment;
        FWx_IDName : String;
        FWx_IDValue : Integer;
        FWx_StretchFactor : Integer;
        FWx_VerticalAlignment : TWxSizerVerticalAlignment;
        FWx_PropertyList : TStringList;
        FInvisibleBGColorString : String;
        FInvisibleFGColorString : String;
        FWx_StatusbarStyleSet:TWxsbrStyleSet;
        FWx_GeneralStyle:TWxStdStyleSet;
        FWx_ToolTip: String;
        FWx_Enabled: Boolean;
        FWx_Hidden: Boolean;
        FWx_HelpText: String;
        FWx_Border: Integer;

      { Private methods of TWxStatusBar }
        procedure AutoInitialize;
        procedure AutoDestroy;

    protected
      { Protected fields of TWxStatusBar }

      { Protected methods of TWxStatusBar }
        procedure Click; override;
        procedure Loaded; override;
        function GenerateControlIDs:String;
        function GenerateEventTableEntries(CurrClassName:String):String;
        function GenerateGUIControlCreation:String;
        function GenerateGUIControlDeclaration:String;
        function GenerateHeaderInclude:String;
        function GenerateImageInclude: string;
        function GetEventList:TStringlist;
        function GetIDName:String;
        function GetIDValue:LongInt;
        function GetParameterFromEventName(EventName: string):String;
        function GetPropertyList:TStringList;
        function GetStretchFactor:Integer;
        function GetTypeFromEventName(EventName: string):string;
        function GetWxClassName:String;
        procedure SaveControlOrientation(ControlOrientation:TWxControlOrientation);
        procedure SetIDName(IDName:String);
        procedure SetIDValue(IDValue:longInt);
        procedure SetStretchFactor(intValue:Integer);
        procedure SetWxClassName(wxClassName:String);
        function GetFGColor:string;
        procedure SetFGColor(strValue:String);
        function GetBGColor:string;
        procedure SetBGColor(strValue:String);

        procedure SetProxyFGColorString(value:String);
        procedure SetProxyBGColorString(value:String);
        
        procedure DummySizerNonInsertableInterfaceProcedure;
    public
      { Public fields and properties of TWxStatusBar }
      { Public fields and properties of TWxTreeCtrl }
       defaultBGColor:TColor;	
       defaultFGColor:TColor;
      { Public methods of TWxStatusBar }
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;

    published
      { Published properties of TWxStatusBar }
        property OnClick;
        property OnResize;
        property Orientation : TWxSizerOrientation read FOrientation write FOrientation default wxHorizontal;
        property SpaceValue : Integer read FSpaceValue write FSpaceValue default 5;
        property Wx_Caption : String read FWx_Caption write FWx_Caption;
        property Wx_Class : String read FWx_Class write FWx_Class;
        property Wx_ControlOrientation : TWxControlOrientation read FWx_ControlOrientation write FWx_ControlOrientation;
        property Wx_EventList : TStringList read FWx_EventList write FWx_EventList;
        property Wx_HorizontalAlignment : TWxSizerHorizontalAlignment read FWx_HorizontalAlignment write FWx_HorizontalAlignment  default wxSZALIGN_CENTER_HORIZONTAL;
        property Wx_IDName : String read FWx_IDName write FWx_IDName;
        property Wx_IDValue : Integer read FWx_IDValue write FWx_IDValue default -1;
        
        property Wx_StatusbarStyleSet :TWxsbrStyleSet read  FWx_StatusbarStyleSet write FWx_StatusbarStyleSet;
        property Wx_GeneralStyle :TWxStdStyleSet read  FWx_GeneralStyle write FWx_GeneralStyle;

	    property Wx_StrechFactor : Integer read FWx_StretchFactor write FWx_StretchFactor;
	    property Wx_StretchFactor : Integer read FWx_StretchFactor write FWx_StretchFactor default 0;
        property Wx_VerticalAlignment : TWxSizerVerticalAlignment read FWx_VerticalAlignment write FWx_VerticalAlignment default wxSZALIGN_CENTER_VERTICAL;
        property InvisibleBGColorString:String read FInvisibleBGColorString write FInvisibleBGColorString;
        property InvisibleFGColorString:String read FInvisibleFGColorString write FInvisibleFGColorString;
        
        property Wx_Hidden : Boolean read FWx_Hidden write FWx_Hidden;
        property Wx_ToolTip : String read FWx_ToolTip write FWx_ToolTip;
        property Wx_HelpText : String read FWx_HelpText write FWx_HelpText;
        property Wx_Enabled : Boolean read FWx_Enabled write FWx_Enabled;
        property Wx_Border : Integer read FWx_Border write FWx_Border default 5;        

  end;

procedure Register;

implementation

procedure Register;
begin
     { Register TWxStatusBar with wxWidgets as its
       default page on the Delphi component palette }
     RegisterComponents('wxWidgets', [TWxStatusBar]);
end;

{ Method to set variable and property values and create objects }
procedure TWxStatusBar.AutoInitialize;
begin
     FWx_PropertyList := TStringList.Create;
     FOrientation := wxHorizontal;
     FSpaceValue := 5;
     FWx_Class := 'wxStatusBar';
     FWx_EventList := TStringList.Create;
     FWx_HorizontalAlignment := wxSZALIGN_CENTER_HORIZONTAL;
     FWx_IDValue := -1;
     FWx_StretchFactor := 0;
     FWx_VerticalAlignment := wxSZALIGN_CENTER_VERTICAL;
     FWx_Enabled:=true;

end; { of AutoInitialize }

{ Method to free any objects created by AutoInitialize }
procedure TWxStatusBar.AutoDestroy;
begin
     FWx_PropertyList.Free;
     FWx_EventList.Free;
end; { of AutoDestroy }

{ Override OnClick handler from TStatusBar }
procedure TWxStatusBar.Click;
begin
     { Code to execute before activating click
       behavior of component's parent class }

     { Activate click behavior of parent }
     inherited Click;

     { Code to execute after click behavior
       of parent }

end;

constructor TWxStatusBar.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }
     FWx_PropertyList.add('Wx_SpinButtonStyle:Spin Control Style');
     FWx_PropertyList.add('Panels :Fields');
     FWx_PropertyList.add('wx_Class:Base Class');
     FWx_PropertyList.add('Wx_Hidden :Hidden');
     FWx_PropertyList.add('Wx_Border : Border ');
     FWx_PropertyList.add('Wx_Default :WxDefault ');
     FWx_PropertyList.add('Wx_HelpText :HelpText ');
     FWx_PropertyList.add('Wx_IDName : IDName ');
     FWx_PropertyList.add('Wx_IDValue : IDValue ');
     FWx_PropertyList.add('Wx_ToolTip :ToolTip ');
     FWx_PropertyList.add('Text:Text');
     FWx_PropertyList.add('Name:Name');
     FWx_PropertyList.add('Wx_Class:Base Class');
     FWx_PropertyList.add('Wx_Enabled:Enabled');
     FWx_PropertyList.add('Left:Left');
     FWx_PropertyList.add('Top:Top');
     FWx_PropertyList.add('Width:Width');
     FWx_PropertyList.add('Height:Height');
     FWx_PropertyList.add('Wx_GeneralStyle : General Styles');
     FWx_PropertyList.add('Wx_StatusbarStyleSet : Statusbar Styles');

     FWx_PropertyList.Add('wxSIMPLE_BORDER:wxSIMPLE_BORDER');
     FWx_PropertyList.Add('wxDOUBLE_BORDER:wxDOUBLE_BORDER');
     FWx_PropertyList.Add('wxSUNKEN_BORDER:wxSUNKEN_BORDER');
     FWx_PropertyList.Add('wxRAISED_BORDER:wxRAISED_BORDER');
     FWx_PropertyList.Add('wxSTATIC_BORDER:wxSTATIC_BORDER');
     FWx_PropertyList.Add('wxTRANSPARENT_WINDOW:wxTRANSPARENT_WINDOW');
     FWx_PropertyList.Add('wxNO_3D:wxNO_3D');
     FWx_PropertyList.Add('wxTAB_TRAVERSAL:wxTAB_TRAVERSAL');
     FWx_PropertyList.Add('wxWANTS_CHARS:wxWANTS_CHARS');
     FWx_PropertyList.Add('wxNO_FULL_REPAINT_ON_RESIZE:wxNO_FULL_REPAINT_ON_RESIZE');
     FWx_PropertyList.Add('wxVSCROLL:wxVSCROLL');
     FWx_PropertyList.Add('wxHSCROLL:wxHSCROLL');
     FWx_PropertyList.Add('wxCLIP_CHILDREN:wxCLIP_CHILDREN');

     //FWx_PropertyList.add('Font : Font');

     FWx_PropertyList.add('Wx_HorizontalAlignment : HorizontalAlignment');
     FWx_PropertyList.add('Wx_VerticalAlignment   : VerticalAlignment');

     FWx_PropertyList.add('Wx_StretchFactor   : StretchFactor');

    FWx_PropertyList.add('wxST_SIZEGRIP:wxST_SIZEGRIP');

end;

destructor TWxStatusBar.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TWxStatusBar.Loaded;
begin
     inherited Loaded;

     { Perform any component setup that depends on the property
       values having been set }

end;


function TWxStatusBar.GenerateControlIDs:String;
begin
     Result:='';
     if (Wx_IDValue > 0) and (trim(Wx_IDName) <> '') then
        Result:=Format('#define %s %d ',[Wx_IDName,Wx_IDValue]);
end;

function TWxStatusBar.GenerateEventTableEntries(CurrClassName:String):String;
begin

     Result:='';

//     if trim(EVT_TEXT_ENTER) <> '' then
//     begin
//          Result:=Format('EVT_TEXT_ENTER(%s,%s::%s)',[WX_IDName,CurrClassName,EVT_TEXT_ENTER]) +'';
//     end;
//
//     if trim(EVT_UPDATE_UI) <> '' then
//     begin
//          Result:=Result+#13+Format('EVT_UPDATE_UI(%s,%s::%s)',[WX_IDName,CurrClassName,EVT_UPDATE_UI]) +'';
//     end;
//
//     if trim(EVT_TEXT) <> '' then
//     begin
//          Result:=Result+#13+Format('EVT_TEXT(%s,%s::%s)',[WX_IDName,CurrClassName,EVT_TEXT]) +'';
//     end;
//
//     if trim(EVT_TEXT_MAXLEN) <> '' then
//     begin
//          Result:=Result+#13+Format('EVT_TEXT_MAXLEN(%s,%s::%s)',[WX_IDName,CurrClassName,EVT_TEXT_MAXLEN]) +'';
//     end;
//
//     if trim(EVT_TEXT_URL) <> '' then
//     begin
//          Result:=Result+#13+Format('EVT_TEXT_URL(%s,%s::%s)',[WX_IDName,CurrClassName,EVT_TEXT_URL]) +'';
//     end;

end;

function TWxStatusBar.GenerateGUIControlCreation:String;


     var
       I: Integer;
     strColorStr:String;
     strStyle,parentName,strAlignment:String;
begin
     Result:='';

//    if (self.Parent is TForm) or (self.Parent is TWxSizerPanel) then
//       parentName:=GetWxWidgetParent(self)
//    else
//       parentName:=self.Parent.name;

    parentName:=GetWxWidgetParent(self);



    strStyle:=GetScrollbarSpecificStyle(self.Wx_GeneralStyle,Wx_StatusbarStyleSet);

    Result:=Format('%s =  new %s(%s, %s %s);',[self.Name,self.wx_Class,parentName,GetWxIDString(self.Wx_IDName,self.Wx_IDValue),strStyle] );

    if self.Panels.Count > 0  then
    begin
        Result:=Result + #13+Format('%s->SetFieldsCount(%d);',[self.Name,self.Panels.Count]);
        for I := 0 to Panels.Count - 1 do    // Iterate
        begin
            Result:=Result + #13+Format('%s->SetStatusText(_("%s"),%d);',[self.Name,GetCppString(self.Panels.items[i].Text),I]);
        end;    // for

        Result:=Result + #13+Format('int %s_Widths[%d];',[self.Name,self.Panels.Count]);

        for I := 0 to Panels.Count - 1 do    // Iterate
        begin
            if I = (Panels.Count - 1) then
                Result:=Result + #13+Format('%s_Widths[%d] = %d;',[self.Name,I,-1])
            else
            Result:=Result + #13+Format('%s_Widths[%d] = %d;',[self.Name,I,self.Panels.items[i].Width]);
        end;    // for

        Result:=Result + #13+Format('%s->SetStatusWidths(%d,%s_Widths);',[self.Name,self.Panels.Count,self.Name]);

    end;

    if trim(self.Wx_ToolTip) <> '' then
        Result:=Result + #13+Format('%s->SetToolTip(wxT(_("%s")));',[self.Name,GetCppString(self.Wx_ToolTip)]);

    if self.Wx_Hidden then
        Result:=Result + #13+Format('%s->Show(false);',[self.Name]);

    if not Wx_Enabled then
        Result:=Result + #13+Format('%s->Enable(false);',[self.Name]);

    if trim(self.Wx_HelpText) <> '' then
        Result:=Result +#13+Format('%s->SetHelpText(_("%s"));',[self.Name,GetCppString(self.Wx_HelpText)]);

    strColorStr:=trim(GetwxColorFromString(InvisibleFGColorString));
    if strColorStr <> '' then
	Result:=Result+#13+Format('%s->SetForegroundColour(%s);',[self.Name,strColorStr]);

    strColorStr:=trim(GetwxColorFromString(InvisibleBGColorString));
    if strColorStr <> '' then
	Result:=Result+#13+Format('%s->SetBackgroundColour(%s);',[self.Name,strColorStr]); 


    //strColorStr:=GetWxFontDeclaration(self.Font);
    //if strColorStr <> '' then
	//Result:=Result+#13+Format('%s->SetFont(%s);',[self.Name,strColorStr]);
            
    if(self.Parent is TWxSizerPanel) then
    begin
        strAlignment:=SizerAlignmentToStr(Wx_HorizontalAlignment) + ' | '+ SizerAlignmentToStr(Wx_VerticalAlignment) +' | wxALL';
        if wx_ControlOrientation = wxControlVertical then
            strAlignment:=SizerAlignmentToStr(Wx_HorizontalAlignment)+ ' | wxALL';

         if wx_ControlOrientation = wxControlHorizontal then
             strAlignment:=SizerAlignmentToStr(Wx_VerticalAlignment)+ ' | wxALL';


         Result:=Result +#13+Format('%s->Add(%s,%d,%s,%d);',[self.Parent.Name,self.Name,self.Wx_StretchFactor,strAlignment,self.Wx_Border]);
    end;


end;

function TWxStatusBar.GenerateGUIControlDeclaration:String;
begin
     Result:='';
     Result:=Format('%s *%s;',[Self.wx_Class,Self.Name]);
end;

function TWxStatusBar.GenerateHeaderInclude:String;
begin
     Result:='';
Result:='#include <wx/statusbr.h>';
end;

function TWxStatusBar.GenerateImageInclude: string;
begin

end;

function TWxStatusBar.GetEventList:TStringlist;
begin
Result:=FWx_EventList;
end;

function TWxStatusBar.GetIDName:String;
begin
     Result:='';
     Result:=wx_IDName;
end;

function TWxStatusBar.GetIDValue:LongInt;
begin
     Result:=wx_IDValue;
end;

function TWxStatusBar.GetParameterFromEventName(EventName: string):String;
begin

end;

function TWxStatusBar.GetPropertyList:TStringList;
begin
     Result:=FWx_PropertyList;
end;

function TWxStatusBar.GetStretchFactor:integer;
begin
    result:=Wx_StretchFactor;
end;

function TWxStatusBar.GetTypeFromEventName(EventName: string):string;
begin

end;

function TWxStatusBar.GetWxClassName:String;
begin
     if trim(wx_Class) = '' then
        wx_Class:='wxStatusBar';
     Result:=wx_Class;
end;

procedure TWxStatusBar.SaveControlOrientation(ControlOrientation:TWxControlOrientation);
begin
wx_ControlOrientation:=ControlOrientation;
end;

procedure TWxStatusBar.SetIDName(IDName:String);
begin
     wx_IDName:=IDName;
end;

procedure TWxStatusBar.SetIDValue(IDValue:longInt);
begin
     Wx_IDValue:=IDVAlue;
end;

procedure TWxStatusBar.SetStretchFactor(intValue:Integer);
begin
    Wx_StretchFactor:=intValue;
end;

procedure TWxStatusBar.SetWxClassName(wxClassName:String);
begin
     wx_Class:=wxClassName;
end;

function TWxStatusBar.GetFGColor:string;
begin
   Result:=FInvisibleFGColorString;
end;

procedure TWxStatusBar.SetFGColor(strValue:String);
begin
    FInvisibleFGColorString:=strValue;
   if IsDefaultColorStr(strValue) then
	self.Font.Color:=defaultFGColor
   else
	self.Font.Color:=GetColorFromString(strValue);
end;
    
function TWxStatusBar.GetBGColor:string;
begin
   Result:=FInvisibleBGColorString;
end;

procedure TWxStatusBar.SetBGColor(strValue:String);
begin
    FInvisibleBGColorString:=strValue;
   if IsDefaultColorStr(strValue) then
	self.Color:=defaultBGColor
   else
	self.Color:=GetColorFromString(strValue);
end;
procedure TWxStatusBar.SetProxyFGColorString(value:String);
begin
    FInvisibleFGColorString:=value;
    self.Color:=GetColorFromString(value);
end;

procedure TWxStatusBar.SetProxyBGColorString(value:String);
begin
   FInvisibleBGColorString:=value;
   self.Font.Color:=GetColorFromString(value);
end;

procedure TWxStatusBar.DummySizerNonInsertableInterfaceProcedure;
begin
end;

end.
