DevPackage Class Reference
The DevPackage(p.) class holds information about package itself which is used by the installer.
#include <PackageClasses.h>
Public Member Functions
DevPackage ()
DevPackage (wxFileConfig *PackageFile)
~DevPackage ()
void LoadFromPackageFile (wxFileConfig *PackageFile=NULL, const wxString &FileName=wxEmptyString)
const wxString WritePackageFileToString ()
void Clear ()
bool BuildPackage (const wxString &FileName, BuildForm *buildForm=NULL, bool Silent=true)
Standard Accessor Functions
Setter and Getter functions for the various standard private members.
const wxString GetPackageName ()
void SetPackageName (const wxString &PackageName)
const wxString GetPackageVersionName ()
void SetPackageVersionName (const wxString &PackageVersionName)
const wxString GetPackageVersion ()
void SetPackageVersion (const wxString &PackageVersion)
const wxString GetMenuName ()
void SetMenuName (const wxString &MenuName)
const wxString GetPackageDescription ()
void SetPackageDesciption (const wxString &PackageDescription)
const wxString GetURL ()
void SetURL (const wxString &URL)
const wxString GetReadMe ()
void SetReadMe (const wxString &ReadMe)
const wxString GetLicenseText ()
void SetLicenseText (const wxString &LicenseText)
const wxString GetPicture ()
void SetPicture (const wxString &Picture)
const wxString GetDependencies ()
void SetDependencies (const wxString &Dependencies)
bool GetReboot ()
void SetReboot (const bool Reboot)
Extended Accessor Functions
Setter and Getter functions for the various extended private members.
bool GetSupportExtendedFormat ()
void SetSupportExtendedFormat (const bool SupportExtendedFormat)
const wxString GetPackagerName ()
void SetPackagerName (const wxString &PackagerName)
const wxString GetPackagerEmail ()
void SetPackagerEmail (const wxString &PackagerEmail)
Private Member Functions
void Init ()
Private Attributes
Standard Private Members
Private memebrs for the standard package format.
wxString _PackageName
wxString _PackageVersionName
wxString _PackageVersion
wxString _MenuName
wxString _PackageDescription
wxString _URL
wxString _Readme
wxString _LicenseText
wxString _Picture
wxString _Dependencies
bool _Reboot
Extended Private Memebers
Private Memebers for the extended package format.
bool _SupportExtendedFormat
wxString _PackagerName
wxString _PackagerEmail
FileInfoList _FileList
IconInfoList _IconList
Detailed Description
The DevPackage(p.) class holds information about package itself which is used by the installer.
The installer will look for the information contained in a DevPak to see where the contained files should be installed to. It also contains information such as readme and license files.
Definition at line 104 of file PackageClasses.h.
Constructor & Destructor Documentation
DevPackage::DevPackage ()
Definition at line 39 of file PackageClasses.cpp.
References Init().
DevPackage::DevPackage (wxFileConfig * PackageFile)
Definition at line 44 of file PackageClasses.cpp.
References Init(), and LoadFromPackageFile().
DevPackage::~DevPackage ()
Definition at line 50 of file PackageClasses.cpp.
Member Function Documentation
bool DevPackage::BuildPackage (const wxString & FileName, BuildForm * buildForm = NULL, bool Silent = true)
Writes a .DevPak file. First it creates a Tar file then it packages this into a bz2 compressed file.
Parameters:
FileName The full file name of the .DevPackage(p.) file used to create absolute locations
buildForm A pointer to the form used to display the progress gauge.
Silent A boolean value which deteremines if the guage and messageboxes are used.
Returns: A boolean value of true if no errors were encountered or false otherwise. NOTE: even on a false value the DevPak may have been built correctly.
See also: WritePackageFileToString()(p.)
Definition at line 240 of file PackageClasses.cpp.
References _FileList, WritePackageFileToString(), BuildForm::WxGauge1, and BuildForm::WxStaticBox1.
void DevPackage::Clear () [inline]
Clears the contents of the DevPackage(p.) class and sets basic defaults.
See also: Init()(p.)
Definition at line 129 of file PackageClasses.h.
References Init().
Referenced by LoadFromPackageFile().
const wxString DevPackage::GetDependencies () [inline]
Getter for the _Dependencies member. Returns the value of the member _Dependencies.
Definition at line 182 of file PackageClasses.h.
References _Dependencies.
const wxString DevPackage::GetLicenseText () [inline]
Getter for the _LicenseText member. Returns the value of the member _LicenseText.
Definition at line 174 of file PackageClasses.h.
References _LicenseText.
const wxString DevPackage::GetMenuName () [inline]
Getter for the _MenuName member. Returns the value of the member _MenuName.
Definition at line 158 of file PackageClasses.h.
References _MenuName.
const wxString DevPackage::GetPackageDescription () [inline]
Getter for the _PackageDescription member. Returns the value of the member _PackageDesciption.
Definition at line 162 of file PackageClasses.h.
References _PackageDescription.
const wxString DevPackage::GetPackageName () [inline]
Getter for the _PackageName member. Returns the value of the member _PackageName.
Definition at line 146 of file PackageClasses.h.
References _PackageName.
const wxString DevPackage::GetPackagerEmail () [inline]
Getter for the _PackagerEmail member. Returns the value of the member _PackagerEmail.
Definition at line 203 of file PackageClasses.h.
References _PackagerEmail.
const wxString DevPackage::GetPackagerName () [inline]
Getter for the _PackagerName member. Returns the value of the member _PackagerName.
Definition at line 199 of file PackageClasses.h.
References _PackagerName.
const wxString DevPackage::GetPackageVersion () [inline]
Getter for the _PackageVersion member. Returns the value of the member _PackageVersion.
Definition at line 154 of file PackageClasses.h.
References _PackageVersion.
const wxString DevPackage::GetPackageVersionName () [inline]
Getter for the _PackageVersionName member. Returns the value of the member _PackageVersionName.
Definition at line 150 of file PackageClasses.h.
References _PackageVersionName.
const wxString DevPackage::GetPicture () [inline]
Getter for the _Picture member. Returns the value of the member _Picture.
Definition at line 178 of file PackageClasses.h.
References _Picture.
const wxString DevPackage::GetReadMe () [inline]
Getter for the _Readme member. Returns the value of the member _Readme.
Definition at line 170 of file PackageClasses.h.
References _Readme.
bool DevPackage::GetReboot () [inline]
Getter for the _Reboot member. Returns the value of the member _Reboot.
Definition at line 186 of file PackageClasses.h.
References _Reboot.
bool DevPackage::GetSupportExtendedFormat () [inline]
Getter for the _SupportExtendedFormat member. Returns the value of the member _SupportExtendedFormat.
Definition at line 195 of file PackageClasses.h.
References _SupportExtendedFormat.
const wxString DevPackage::GetURL () [inline]
Getter for the _URL member. Returns the value of the member _URL.
Definition at line 166 of file PackageClasses.h.
References _URL.
void DevPackage::Init () [private]
Clears the contents of the DevPackage(p.) class and sets basic defaults. Called by the constructors and Clear function.
See also: Clear()(p.)
DevPackage()(p.)
DevPackage(wxFileConfig * PackageFile)(p.)
Definition at line 54 of file PackageClasses.cpp.
References _Dependencies, _FileList, _IconList, _LicenseText, _MenuName, _PackageDescription, _PackageName, _PackagerEmail, _PackagerName, _PackageVersion, _PackageVersionName, _Picture, _Readme, _Reboot, _SupportExtendedFormat, and _URL.
Referenced by Clear(), and DevPackage().
void DevPackage::LoadFromPackageFile (wxFileConfig * PackageFile = NULL, const wxString & FileName = wxEmptyString)
Creates a DevPackage(p.) from a .DevPackage(p.) file.
Parameters:
PackageFile a wxFileConfig class which is the file to load from.
FileName The full file name on the system used to create absolute loacations.
See also: WritePackageFileToString()(p.)
Definition at line 74 of file PackageClasses.cpp.
References _Dependencies, _FileList, _LicenseText, _MenuName, _PackageDescription, _PackageName, _PackagerEmail, _PackagerName, _PackageVersion, _PackageVersionName, _Picture, _Readme, _Reboot, _SupportExtendedFormat, _URL, Clear(), EXTENDED_SETUP_SECTION, FILES_SECTION, and SETUP_SECTION.
Referenced by DevPackage().
void DevPackage::SetDependencies (const wxString & Dependencies) [inline]
Setter for the _Dependencies member. Sets the value of the member _Dependencies.
Definition at line 184 of file PackageClasses.h.
References _Dependencies.
void DevPackage::SetLicenseText (const wxString & LicenseText) [inline]
Setter for the _LicenseText member. Sets the value of the member _LicenseText.
Definition at line 176 of file PackageClasses.h.
References _LicenseText.
void DevPackage::SetMenuName (const wxString & MenuName) [inline]
Setter for the _MenuName member. Sets the value of the member _MenuName.
Definition at line 160 of file PackageClasses.h.
References _MenuName.
void DevPackage::SetPackageDesciption (const wxString & PackageDescription) [inline]
Setter for the _PackageDescription member. Sets the value of the member _PackageDesciption.
Definition at line 164 of file PackageClasses.h.
References _PackageDescription.
void DevPackage::SetPackageName (const wxString & PackageName) [inline]
Setter for the _PackageName member. Sets the value of the member _PackageName.
Definition at line 148 of file PackageClasses.h.
References _PackageName.
void DevPackage::SetPackagerEmail (const wxString & PackagerEmail) [inline]
Setter for the _PackagerEmail member. Sets the value of the member _PackagerEmail.
Definition at line 205 of file PackageClasses.h.
References _PackagerEmail.
void DevPackage::SetPackagerName (const wxString & PackagerName) [inline]
Setter for the _PackagerName member. Sets the value of the member _PackagerName.
Definition at line 201 of file PackageClasses.h.
References _PackagerName.
void DevPackage::SetPackageVersion (const wxString & PackageVersion) [inline]
Setter for the _PackageVersion member. Sets the value of the member _PackageVersion.
Definition at line 156 of file PackageClasses.h.
References _PackageVersion.
void DevPackage::SetPackageVersionName (const wxString & PackageVersionName) [inline]
Setter for the _PackageVersionName member. Sets the value of the member _PackageVersionName.
Definition at line 152 of file PackageClasses.h.
References _PackageVersionName.
void DevPackage::SetPicture (const wxString & Picture) [inline]
Setter for the _Picture member. Sets the value of the member _Picture.
Definition at line 180 of file PackageClasses.h.
References _Picture.
void DevPackage::SetReadMe (const wxString & ReadMe) [inline]
Setter for the _Readme member. Sets the value of the member _Readme.
Definition at line 172 of file PackageClasses.h.
References _Readme.
void DevPackage::SetReboot (const bool Reboot) [inline]
Setter for the _Reboot member. Sets the value of the member _Reboot.
Definition at line 188 of file PackageClasses.h.
References _Reboot.
void DevPackage::SetSupportExtendedFormat (const bool SupportExtendedFormat) [inline]
Setter for the _SupportExtendedFormat member. Sets the value of the member _SupportExtendedFormat.
Definition at line 197 of file PackageClasses.h.
References _SupportExtendedFormat.
void DevPackage::SetURL (const wxString & URL) [inline]
Setter for the _URL member. Sets the value of the member _URL.
Definition at line 168 of file PackageClasses.h.
References _URL.
const wxString DevPackage::WritePackageFileToString ()
Writes a .DevPackage(p.) file to a string this is needed since wxFileConfig does not add a space at the start of the file.
See also: LoadFromPackageFile()(p.)
Returns: A wxString containing the contents of the file
Definition at line 174 of file PackageClasses.cpp.
References _Dependencies, _FileList, _LicenseText, _MenuName, _PackageDescription, _PackageName, _PackagerEmail, _PackagerName, _PackageVersion, _PackageVersionName, _Picture, _Readme, _Reboot, _SupportExtendedFormat, _URL, DEVPAK_SUBVERSION, DEVPAK_VERSION, and PATH_FORMAT.
Referenced by BuildPackage().
Member Data Documentation
wxString DevPackage::_Dependencies [private]
Holds the list of package names this package depends on. This corresponds to Dependencies section in the .DevPackage(p.) file.
Definition at line 241 of file PackageClasses.h.
Referenced by GetDependencies(), Init(), LoadFromPackageFile(), SetDependencies(), and WritePackageFileToString().
FileInfoList DevPackage::_FileList [private]
Holds the list of file contained in the package. This corresponds to files in the Files section of the .DevPackage(p.) file.
Definition at line 257 of file PackageClasses.h.
Referenced by BuildPackage(), Init(), LoadFromPackageFile(), and WritePackageFileToString().
IconInfoList DevPackage::_IconList [private]
Holds the list of menu entries and icons to add to the start menu. This corresponds to the Icons section of the .DevPackage(p.) file.
Definition at line 259 of file PackageClasses.h.
Referenced by Init().
wxString DevPackage::_LicenseText [private]
Holds the license information for the package contents. This corresponds to License section in the .DevPackage(p.) file.
Definition at line 237 of file PackageClasses.h.
Referenced by GetLicenseText(), Init(), LoadFromPackageFile(), SetLicenseText(), and WritePackageFileToString().
wxString DevPackage::_MenuName [private]
Holds the menu name the package will occupy in the start menu. This corresponds to MenuName section in the .DevPackage(p.) file.
Definition at line 229 of file PackageClasses.h.
Referenced by GetMenuName(), Init(), LoadFromPackageFile(), SetMenuName(), and WritePackageFileToString().
wxString DevPackage::_PackageDescription [private]
Holds the package description. This corresponds to Description section in the .DevPackage(p.) file.
Definition at line 231 of file PackageClasses.h.
Referenced by GetPackageDescription(), Init(), LoadFromPackageFile(), SetPackageDesciption(), and WritePackageFileToString().
wxString DevPackage::_PackageName [private]
Holds the package name. This corresponds to AppName section in the .DevPackage(p.) file.
Definition at line 223 of file PackageClasses.h.
Referenced by GetPackageName(), Init(), LoadFromPackageFile(), SetPackageName(), and WritePackageFileToString().
wxString DevPackage::_PackagerEmail [private]
Holds the packager's email addess. This corresponds to PackagerEmail section in the extended section of the .DevPackage(p.) file.
Definition at line 255 of file PackageClasses.h.
Referenced by GetPackagerEmail(), Init(), LoadFromPackageFile(), SetPackagerEmail(), and WritePackageFileToString().
wxString DevPackage::_PackagerName [private]
Holds the packager's name. This corresponds to Packager section in the extended section of the .DevPackage(p.) file.
Definition at line 253 of file PackageClasses.h.
Referenced by GetPackagerName(), Init(), LoadFromPackageFile(), SetPackagerName(), and WritePackageFileToString().
wxString DevPackage::_PackageVersion [private]
Holds the package version number. This corresponds to AppVersion section in the .DevPackage(p.) file.
Definition at line 227 of file PackageClasses.h.
Referenced by GetPackageVersion(), Init(), LoadFromPackageFile(), SetPackageVersion(), and WritePackageFileToString().
wxString DevPackage::_PackageVersionName [private]
Holds the package name and version. This corresponds to AppVerName section in the .DevPackage(p.) file.
Definition at line 225 of file PackageClasses.h.
Referenced by GetPackageVersionName(), Init(), LoadFromPackageFile(), SetPackageVersionName(), and WritePackageFileToString().
wxString DevPackage::_Picture [private]
Holds a file name of a picture to be displayed. This corresponds to Picture section in the .DevPackage(p.) file.
Definition at line 239 of file PackageClasses.h.
Referenced by GetPicture(), Init(), LoadFromPackageFile(), SetPicture(), and WritePackageFileToString().
wxString DevPackage::_Readme [private]
Holds the Readme file name. This corresponds to Readme section in the .DevPackage(p.) file.
Definition at line 235 of file PackageClasses.h.
Referenced by GetReadMe(), Init(), LoadFromPackageFile(), SetReadMe(), and WritePackageFileToString().
bool DevPackage::_Reboot [private]
Holds the reboot value specifying whether a reboot is needed after installation. This corresponds to Reboot section in the .DevPackage(p.) file.
Definition at line 243 of file PackageClasses.h.
Referenced by GetReboot(), Init(), LoadFromPackageFile(), SetReboot(), and WritePackageFileToString().
bool DevPackage::_SupportExtendedFormat [private]
Holds a value to see if this package supports extended information.
Definition at line 251 of file PackageClasses.h.
Referenced by GetSupportExtendedFormat(), Init(), LoadFromPackageFile(), SetSupportExtendedFormat(), and WritePackageFileToString().
wxString DevPackage::_URL [private]
Holds the URL to a website related to the package. This corresponds to Url section in the .DevPackage(p.) file.
Definition at line 233 of file PackageClasses.h.
Referenced by GetURL(), Init(), LoadFromPackageFile(), SetURL(), and WritePackageFileToString().
The documentation for this class was generated from the following files:
C:/Dev-Cpp/WxProjects/PackMaker2Extended/PackageClasses.h
C:/Dev-Cpp/WxProjects/PackMaker2Extended/PackageClasses.cpp